### ISSUE TITLE
DTG can't locate functions when module defines a DefaultCommandPrefix

### ISSUE THREAD

**Issue by ebekker** [msorens/DocTreeGenerator#7]
When a module defines the `DefaultCommandPrefix` property in its manifest, DTG can't properly locate/inspect help details of the functions (cmdlets) exported from the module.

I've verified this is true for both binary and script modules.

**Comment by ebekker** [comment]
The source of the problem appears to be in the `Generate-FunctionPages` routine -- where it's getting the list of commands from the `Get-Command -Module $moduleName` call -- this returns a set of `System.Management.Automation.FunctionInfo` instances.

While each instance appears to have correct individual about each command, when you invoke the `.ToString()` on this type, it returns a form of the command where the DefaultCommandPrefix is *doubled*.

For example, if I have a module `TestModule` that defines a DefaultCommandPrefix of `TestMod`, and two exported functions:
* `Get-Min`
* `Get-Max`

Then by default, upon importing this module, I would expect these routines to become available as:
* `Get-TestModMin`
* `Get-TestModMax`

But when the `FunctionInfo.ToString()` returns them as:
* `Get-TestModTestModMin`
* `Get-TestModTestModMax`

**Comment by msorens** [comment]
Committed Eugene's patch on 2017.06.19
